"""
LLM-based planner using Claude to generate structured dispatch plans.
Determines which agents to invoke and in what order for complex financial queries.
"""
from __future__ import annotations

import json
import re
from typing import Any, Optional

from pydantic import BaseModel, Field
from loguru import logger
from tenacity import (
    retry,
    stop_after_attempt,
    wait_exponential,
)

from config.settings import settings


# ─── Dispatch Schema ──────────────────────────────────────────────────────────

DISPATCH_SCHEMA = {
    "type": "object",
    "properties": {
        "steps": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "step_id": {"type": "integer", "description": "Step index starting from 0"},
                    "agent": {
                        "type": "string",
                        "enum": ["qa", "credit", "graph"],
                        "description": "Which agent to invoke",
                    },
                    "action": {
                        "type": "string",
                        "description": "Specific action for the agent",
                    },
                    "inputs": {
                        "type": "object",
                        "description": "Input parameters for the agent action",
                    },
                    "depends_on": {
                        "type": "array",
                        "items": {"type": "integer"},
                        "description": "step_ids this step depends on (empty = can run immediately)",
                    },
                    "priority": {
                        "type": "string",
                        "enum": ["high", "medium", "low"],
                        "default": "medium",
                    },
                },
                "required": ["step_id", "agent", "action", "inputs", "depends_on"],
            },
        },
        "final_synthesis": {
            "type": "string",
            "description": "How to synthesize results from all steps into final answer",
        },
        "query_type": {
            "type": "string",
            "enum": ["loan_application", "qa_only", "credit_only", "full_analysis"],
            "description": "Type of query being processed",
        },
    },
    "required": ["steps", "final_synthesis"],
}


# ─── Pydantic Models ──────────────────────────────────────────────────────────

class DispatchStep(BaseModel):
    """A single step in the dispatch plan."""
    step_id: int
    agent: str = Field(description="qa/credit/graph")
    action: str
    inputs: dict = Field(default_factory=dict)
    depends_on: list[int] = Field(default_factory=list)
    priority: str = "medium"
    result: Optional[Any] = None
    status: str = "pending"  # pending/running/done/failed


class DispatchPlan(BaseModel):
    """Structured execution plan generated by the planner."""
    steps: list[DispatchStep]
    final_synthesis: str
    query_type: str = "full_analysis"
    raw_planner_output: str = ""

    def get_ready_steps(self) -> list[DispatchStep]:
        """Return steps whose dependencies are all completed."""
        completed_ids = {
            s.step_id for s in self.steps if s.status == "done"
        }
        ready = []
        for step in self.steps:
            if step.status != "pending":
                continue
            if all(dep in completed_ids for dep in step.depends_on):
                ready.append(step)
        return ready

    def all_done(self) -> bool:
        return all(s.status in ("done", "failed") for s in self.steps)

    def get_results_map(self) -> dict[int, Any]:
        return {s.step_id: s.result for s in self.steps if s.result is not None}

    def summary(self) -> str:
        lines = [f"DispatchPlan ({len(self.steps)} steps, type={self.query_type}):"]
        for step in self.steps:
            deps = f" (depends on: {step.depends_on})" if step.depends_on else ""
            lines.append(f"  Step {step.step_id}: [{step.agent}] {step.action}{deps}")
        return "\n".join(lines)


# ─── Planner ──────────────────────────────────────────────────────────────────

class FinancialPlanner:
    """
    LLM-based planner that generates structured dispatch plans using Claude.

    Given a user query and enterprise context, the planner determines:
    - Which agents to invoke (qa, credit, graph)
    - What actions each agent should perform
    - Execution order and dependencies
    - How to synthesize results
    """

    PLANNER_SYSTEM_PROMPT = """你是一个智能金融平台的规划器（Planner），负责将用户的金融查询分解为结构化的执行计划。

你有三个可用的执行代理：
1. **qa** (问答代理): 从知识库检索文档，回答关于金融政策、产品条件、行业规定等问题
   - 适用于：政策咨询、产品信息查询、条件确认

2. **credit** (信贷代理): 执行完整的信用评估
   - 适用于：贷款申请审核、信用评分、风险评估
   - 包含：财务分析、信用评分、供应链评估、税务合规

3. **graph** (图谱代理): 从知识图谱查询行业和供应链信息
   - 适用于：行业分析、竞争格局、供应链关系
   - 先于credit代理运行，提供行业背景

执行原则：
- 对于贷款申请：先运行graph获取行业背景，再运行credit评分，最后qa回答补充问题
- 对于简单咨询：只运行qa即可
- 对于信用查询：运行graph + credit
- 注意depends_on决定执行顺序（并行执行效率更高）

你必须以JSON格式返回计划，严格遵循以下Schema：
"""

    def __init__(self, anthropic_client: Optional[Any] = None):
        self._client = anthropic_client or self._init_client()

    def _init_client(self) -> Optional[Any]:
        try:
            import anthropic
            return anthropic.Anthropic(api_key=settings.anthropic.api_key)
        except Exception as e:
            logger.warning(f"Planner: Anthropic client init failed: {e}")
            return None

    @retry(
        stop=stop_after_attempt(settings.app.max_retries),
        wait=wait_exponential(
            multiplier=settings.app.retry_multiplier,
            min=settings.app.retry_wait_min,
            max=settings.app.retry_wait_max,
        ),
        reraise=True,
    )
    def plan(
        self,
        query: str,
        enterprise_context: Optional[dict] = None,
        use_thinking: bool = True,
    ) -> DispatchPlan:
        """
        Generate a dispatch plan for the given query and context.

        Args:
            query: User's natural language query.
            enterprise_context: Enterprise data for context-aware planning.
            use_thinking: Enable Claude adaptive thinking for complex planning.

        Returns:
            DispatchPlan with ordered steps and dependencies.
        """
        logger.info(f"Planner.plan: '{query[:80]}'")

        if self._client is None:
            logger.warning("No Anthropic client; using heuristic plan")
            return self._heuristic_plan(query, enterprise_context)

        try:
            plan_json = self._call_claude_for_plan(query, enterprise_context, use_thinking)
            plan = self._parse_plan(plan_json)
            logger.info(f"Plan generated: {plan.summary()}")
            return plan
        except Exception as e:
            logger.warning(f"LLM planning failed: {e}. Using heuristic fallback.")
            return self._heuristic_plan(query, enterprise_context)

    def _call_claude_for_plan(
        self,
        query: str,
        enterprise_context: Optional[dict],
        use_thinking: bool,
    ) -> str:
        """Call Claude to generate the dispatch plan."""
        system_text = (
            self.PLANNER_SYSTEM_PROMPT
            + "\n\n"
            + json.dumps(DISPATCH_SCHEMA, ensure_ascii=False, indent=2)
        )

        context_str = ""
        if enterprise_context:
            company = enterprise_context.get("company_name", "")
            industry = enterprise_context.get("industry", "")
            loan_amount = enterprise_context.get("loan_request", {}).get("amount", 0)
            context_str = (
                f"\n\n企业背景：\n"
                f"- 企业名称：{company}\n"
                f"- 行业：{industry}\n"
                f"- 贷款申请金额：{loan_amount:,.0f}元\n"
            )

        user_content = (
            f"请为以下查询生成执行计划：\n\n"
            f"用户查询：{query}"
            f"{context_str}\n\n"
            "请严格按照JSON Schema生成计划，只返回JSON，不要有其他说明。"
        )

        kwargs = {
            "model": settings.anthropic.model,
            "max_tokens": 3000,
            "system": [
                {
                    "type": "text",
                    "text": system_text,
                    "cache_control": {"type": "ephemeral"},
                }
            ],
            "messages": [{"role": "user", "content": user_content}],
        }

        if use_thinking:
            kwargs["thinking"] = {"type": "adaptive"}
        else:
            kwargs["output_config"] = {"effort": "medium"}

        with self._client.messages.stream(**kwargs) as stream:
            message = stream.get_final_message()

        text_parts = [
            block.text for block in message.content
            if hasattr(block, "text")
        ]
        return "\n".join(text_parts)

    def _parse_plan(self, raw_json: str) -> DispatchPlan:
        """Parse Claude's JSON output into a DispatchPlan."""
        # Extract JSON from response
        data = None

        for pattern in [
            r"```json\s*([\s\S]+?)\s*```",
            r"```\s*([\s\S]+?)\s*```",
            r"(\{[\s\S]+\})",
        ]:
            match = re.search(pattern, raw_json)
            if match:
                try:
                    data = json.loads(match.group(1))
                    break
                except Exception:
                    continue

        if data is None:
            try:
                data = json.loads(raw_json)
            except Exception:
                raise ValueError(f"Could not parse plan JSON: {raw_json[:200]}")

        # Build DispatchPlan
        steps = []
        for step_data in data.get("steps", []):
            step = DispatchStep(
                step_id=step_data.get("step_id", len(steps)),
                agent=step_data.get("agent", "qa"),
                action=step_data.get("action", "answer"),
                inputs=step_data.get("inputs", {}),
                depends_on=step_data.get("depends_on", []),
                priority=step_data.get("priority", "medium"),
            )
            steps.append(step)

        if not steps:
            raise ValueError("Plan has no steps")

        return DispatchPlan(
            steps=steps,
            final_synthesis=data.get("final_synthesis", "综合所有代理结果"),
            query_type=data.get("query_type", "full_analysis"),
            raw_planner_output=raw_json,
        )

    @staticmethod
    def _heuristic_plan(
        query: str,
        enterprise_context: Optional[dict],
    ) -> DispatchPlan:
        """
        Heuristic planning when Claude is unavailable.
        Determines plan based on simple keyword matching.
        """
        query_lower = query.lower()
        has_enterprise = enterprise_context is not None
        has_loan_request = bool(
            enterprise_context
            and enterprise_context.get("loan_request", {}).get("amount")
        )

        # Keywords for different plan types
        credit_keywords = ["贷款", "信用", "融资", "评分", "审批", "申请", "loan", "credit"]
        qa_keywords = ["什么", "如何", "条件", "政策", "介绍", "what", "how", "policy"]
        graph_keywords = ["行业", "供应链", "竞争", "市场", "industry", "supply"]

        is_credit_query = any(k in query_lower for k in credit_keywords) or has_loan_request
        is_graph_query = any(k in query_lower for k in graph_keywords)
        is_qa_query = any(k in query_lower for k in qa_keywords)

        steps = []

        if is_graph_query or (is_credit_query and has_enterprise):
            steps.append(DispatchStep(
                step_id=0,
                agent="graph",
                action="analyze_industry",
                inputs={
                    "enterprise_info": enterprise_context or {},
                },
                depends_on=[],
                priority="high",
            ))

        if is_credit_query and has_enterprise:
            depends = [0] if steps else []
            steps.append(DispatchStep(
                step_id=len(steps),
                agent="credit",
                action="assess",
                inputs={
                    "enterprise_data": enterprise_context or {},
                },
                depends_on=depends,
                priority="high",
            ))

        if is_qa_query or not steps:
            steps.append(DispatchStep(
                step_id=len(steps),
                agent="qa",
                action="answer",
                inputs={"question": query},
                depends_on=[],
                priority="medium",
            ))

        query_type = "loan_application" if is_credit_query else ("qa_only" if is_qa_query else "full_analysis")

        plan = DispatchPlan(
            steps=steps,
            final_synthesis="综合所有代理结果，给出完整的金融分析报告",
            query_type=query_type,
        )
        logger.info(f"Heuristic plan: {plan.summary()}")
        return plan
